package keymap

// fixed is every key the TUI answers that no operation owns (decision 1), with
// what it means there. The registry rows come first, in registry order; the
// aliases the registry does not list follow. internal/tui's tests hold this
// list against the registry and against the literal keys its handlers match,
// so a new fixed key that is not recorded here fails a test rather than
// leaving an override free to shadow it.
var fixed = []Fixed{
	{"global", "tab", "move to the next task tab"},
	{"global", "ctrl+v", "paste into the focused field"},
	{"global", "esc", "close one layer"},
	{"global", "ctrl+c", "quit the TUI"},
	{"task table", "down", "move the selection"},
	{"task table", "g", "group the tasks"},
	{"task table", "space", "select this task for a bulk action"},
	{"task table", "V", "select every task the filter is showing, or clear that selection"},
	{"task table", "L", "expand or collapse the selected fan-out's lanes, as indented rows under it"},
	{"task table", "left", "collapse the group you are in"},
	{"task table", "right", "expand the collapsed group under the cursor, one level"},
	{"task table", "C", "collapse every group"},
	{"task table", "O", "expand every group"},
	{"timeline", "tab", "move between Steps & Attempts, Task Details, Output and Diff"},
	{"timeline", "]", "move to the next task view"},
	{"timeline", "down", "select an attempt"},
	{"timeline", "enter", "open the selected attempt in the Output tab, or open the folded iteration/round tier the cursor is on"},
	{"timeline", "space", "open or close the iteration/round tier the cursor is in"},
	{"timeline", "right", "open the folded tier the cursor is in"},
	{"timeline", "left", "close the tier the cursor is in"},
	{"timeline", "O", "open every iteration and round tier of this task"},
	{"timeline", "C", "close every one"},
	{"timeline", "U", "open this lane's parent task"},
	{"task details", "tab", "move between the task's views"},
	{"task details", "]", "move to the next task view"},
	{"task details", "down", "select a task-detail section"},
	{"task details", "P", "push this task's branch to origin and open its pull request"},
	{"task details", "U", "open this lane's parent task"},
	{"output", "tab", "move between Steps & Attempts, Task Details, Output and Diff"},
	{"output", "]", "move to the next task view"},
	{"output", "f", "follow the live output again"},
	{"output", "v", "show more or less"},
	{"output", "ctrl+o", "show the assistant's original Markdown instead of the rendered view"},
	{"output", "ctrl+y", "copy an assistant message, its plain text, or one of its code blocks"},
	{"output", "ctrl+l", "list the links in the assistant's messages"},
	{"output", "down", "scroll"},
	{"output", "right", "select which attempt's output to show"},
	{"output", "<", "previous fan-out lane in the Output pane"},
	{"output", ">", "next fan-out lane in the Output pane"},
	{"diff", "tab", "move between Steps & Attempts, Task Details, Output and Diff"},
	{"diff", "]", "move to the next task view"},
	{"diff", "down", "move between the files"},
	{"diff", "enter", "expand or collapse the file under the cursor"},
	{"diff", "O", "expand every file"},
	{"diff", "C", "collapse every file"},
	{"new task", "enter", "open the focused field's editor or picker"},
	{"new task", "+", "nudge the priority"},
	{"new task", "ctrl+s", "create the task"},
	{"new task fields", "down", "move between the fields"},
	{"new task fields", "enter", "edit the row under the cursor, toggle a declared boolean, or open a declared enum's list"},
	{"new task fields", "left", "step a declared enum or boolean through its values in place"},
	{"new task fields", "esc", "close the editor and keep the fields"},
	{"archived tasks", ">", "next page of the archive"},
	{"archived tasks", "space", "select this task for the bulk delete"},
	{"archived chats", ">", "next page of the archive"},
	{"chats", "left", "collapse the project group"},
	{"chats", "right", "expand the project group"},
	{"chat", "enter", "send the message"},
	{"chat", "ctrl+x", "stop the running turn"},
	{"chat", "ctrl+r", "how much of the conversation to show"},
	{"chat", "pgup", "scroll the conversation back"},
	{"chat", "ctrl+g", "jump to the live end and follow it again"},
	{"chat", "ctrl+t", "hand the worktree and branch to a new task"},
	{"chat", "esc", "back to the chats board"},
	{"chat", "ctrl+o", "show the assistant's original Markdown instead of the rendered view"},
	{"chat", "ctrl+y", "copy an assistant message, its plain text, or one of its code blocks"},
	{"chat", "ctrl+l", "list the links in the assistant's messages"},
	{"new chat", "ctrl+s", "create the chat and open it"},
	{"new chat", "enter", "open the focused field's list, or move on from a text field"},
	{"new chat", "tab", "next field"},
	{"new chat", "left", "step the project and agent fields in place"},
	{"new chat", "esc", "close an open list, else discard the draft"},
	{"projects", "enter", "edit the selected project"},
	{"projects", "ctrl+s", "in the form"},
	{"workflows", "enter", "show the entry's steps"},
	{"workflows", "g", "draw the workflow as a control-flow graph"},
	{"workflows", "i", "edit the entry in a structured form"},
	{"workflows", "f", "fork the entry into another scope, where it shadows the original"},
	{"workflow editor", "up", "move between rows"},
	{"workflow editor", "down", "move between rows"},
	{"workflow editor", "enter", "edit the row, cycle its values, or descend into a nested body"},
	{"workflow editor", "esc", "leave the nested body, then the editor"},
	{"workflow editor", "K", "move the item up"},
	{"workflow editor", "J", "move the item up"},
	{"workflow editor", "ctrl+s", "in the multi-line pane"},
	{"workflow create", "tab", "move between the scope and the file name"},
	{"workflow create", "left", "choose the scope"},
	{"workflow create", "right", "choose the scope"},
	{"workflow create", "enter", "write the file and open it in the editor"},
	{"workflow create", "esc", "close the prompt"},
	{"workflow graph", "down", "move the selection"},
	{"workflow graph", "shift+down", "pan the canvas"},
	{"workflow graph", "tab", "walk the nodes in source order"},
	{"workflow graph", "enter", "open the selected node in full"},
	{"step detail", "down", "scroll the detail"},
	{"step detail", "esc", "close the detail, back to the graph with the same node selected"},
	{"task workflow", "down", "move the selection"},
	{"task workflow", "shift+down", "pan the canvas"},
	{"task workflow", "5", "the workflow this task ran, with what each step did on it"},
	{"task step details", "6", "what this attempt was handed"},
	{"task step details", "down", "select an attempt"},
	{"task pull request", "7", "this task's pull request, with a live row per check on its head commit"},
	{"task pull request", "down", "select a check"},
	{"task pull request", "u", "unlink this pull request from the task"},
	{"task pull request", "m", "merge this pull request"},
	{"task pull request", "X", "close this pull request without merging, or reopen a closed one"},
	{"task pull request", "i", "comment on this pull request"},
	{"task pull request", "ctrl+r", "re-run the failed jobs of the selected check's GitHub Actions run"},
	{"pull requests", "enter", "open the workspace of the task that claims this pull request"},
	{"pull requests", "l", "link this pull request to a task in the same project"},
	{"pull requests", "P", "open a pull request for a task that has none"},
	{"pull requests", "u", "unlink it"},
	{"pull requests", "down", "move the selection"},
	{"daemon", "f", "follow the end of the log again"},
	{"daemon", "down", "scroll the log"},
	{"daemon", "tab", "move between the config list and the log pane"},
	{"daemon", "enter", "edit the selected configuration key"},
	{"daemon", "i", "make vincent claude's status line, or remove it"},
	{"daemon", "S", "install the agent skills vincent publishes"},
	{"agent skills", "enter", "run the install"},
	{"agent skills", "n", "not now"},
	{"agent skills", "esc", "close without installing anything"},
	{"config editor", "left", "choose a value, for a key with a fixed vocabulary"},
	{"config editor", "enter", "apply the change"},
	{"config editor", "y", "confirm a key that decides what the daemon executes or exposes"},
	{"config editor", "esc", "close the editor without saving"},
	{"triggers", "down", "move the selection"},
	{"triggers", "enter", "open the selected trigger in the form"},
	{"triggers", "space", "enable or disable the selected trigger"},
	{"triggers", "T", "dry-run a sample event through the trigger's filter"},
	{"triggers", "X", "poll the source once and judge what it returns"},
	{"triggers", "tab", "move between the trigger list and its delivery ledger"},
	{"triggers", "B", "open triggers.enabled, the global switch, in the daemon view's editor"},
	{"trigger ledger", "down", "move through the deliveries"},
	{"trigger ledger", "enter", "open the task the delivery created or acted on"},
	{"trigger ledger", "tab", "back to the trigger list"},
	{"trigger form", "down", "move between the trigger's fields"},
	{"trigger form", "enter", "edit the field"},
	{"trigger form", "esc", "close the form"},
	{"trigger create", "tab", "move between the starter's inputs"},
	{"trigger create", "enter", "write the new trigger"},
	{"trigger create", "esc", "close the prompt"},
	{"trigger dry run", "ctrl+s", "run the dry run on the sample event"},
	{"trigger dry run", "esc", "close the dry run"},
	{"answer form", "space", "pick an option"},
	{"answer form", "enter", "submit the answer"},
	{"answer form", "ctrl+t", "read this task's details without leaving the form"},
	{"answer form", "esc", "close the popup without answering"},
	{"repair form", "enter", "edit the row under the cursor"},
	{"repair form", "ctrl+s", "start the repair agent"},
	{"repair form", "ctrl+t", "read this task's details without leaving the form"},
	{"repair form", "esc", "close the popup without repairing"},
	{"follow-up form", "enter", "edit the row under the cursor"},
	{"follow-up form", "ctrl+s", "start the follow-up run"},
	{"follow-up form", "ctrl+t", "read this task's details without leaving the form"},
	{"follow-up form", "esc", "close the popup without running anything"},
	{"open a pull request", "enter", "edit the row under the cursor"},
	{"open a pull request", "space", "toggle draft / ready for review, on the draft row"},
	{"open a pull request", "ctrl+s", "push the branch to origin and open the pull request"},
	{"open a pull request", "ctrl+o", "open GitHub's own new-pull-request page with this prefill instead"},
	{"open a pull request", "esc", "close the popup without sending anything"},
	{"merge a pull request", "left", "choose the merge method"},
	{"merge a pull request", "y", "merge with the chosen method at the head commit shown"},
	{"merge a pull request", "n", "close without merging"},
	{"merge a pull request", "esc", "close without merging"},
	{"comment on a pull request", "enter", "type the comment in the popup"},
	{"comment on a pull request", "ctrl+s", "post the comment"},
	{"comment on a pull request", "esc", "stop typing"},
	{"confirm a pull request write", "y", "yes"},
	{"confirm a pull request write", "n", "no"},

	// Keys the handlers answer that the registry names only in a label, or
	// not at all: the vim aliases, the rest of a pair, the confirmations'
	// letters. None may become an operation's key.
	{"global", "shift+tab", "move to the previous task tab"},
	{"global", "r", "retry the connection while disconnected"},
	{"lists and panes", "j", "move down (vim)"},
	{"lists and panes", "k", "move up (vim)"},
	{"lists and panes", "h", "move left (vim)"},
	{"lists and panes", "l", "move right (vim)"},
	{"lists and panes", "G", "jump to the end (vim)"},
	{"lists and panes", "home", "jump to the start"},
	{"lists and panes", "end", "jump to the end"},
	{"lists and panes", "pgup", "page up"},
	{"lists and panes", "pgdown", "page down"},
	{"lists and panes", "ctrl+d", "half a page down (viewport)"},
	{"lists and panes", "ctrl+u", "half a page up (viewport)"},
	{"lists and panes", "b", "page up (viewport)"},
	{"lists and panes", "u", "half a page up (viewport)"},
	{"task workspace", "[", "move to the previous task view"},
	{"task workspace", "1", "jump to Steps & Attempts"},
	{"task workspace", "2", "jump to Task Details"},
	{"task workspace", "3", "jump to Output"},
	{"task workspace", "4", "jump to Diff"},
	{"output", "d", "switch between the Output and Diff tabs"},
	{"projects", "e", "edit the selected project"},
	{"daemon", "e", "edit the selected configuration key"},
	{"triggers", "i", "open the selected trigger in the form"},
	{"new task", "-", "nudge the priority down"},
	{"new task", "=", "nudge the priority up"},
	{"new task", "_", "nudge the priority down"},
	{"confirmations", "Y", "yes"},
	{"confirmations", "N", "no"},
	{"confirmations", "n", "no"},
	{"confirmations", "b", "delete the branch too"},
}
